id: asdf://astropy.org/astropy/manifests/astropy-1.1.0
extension_uri: asdf://astropy.org/astropy/extensions/astropy-1.1.0
title: Astropy extension 1.1.0
description: |-
  A set of tags for serializing astropy objects.  This does not include most
  model classes, which are handled by an implementation of the ASDF
  transform extension.
asdf_standard_requirement:
  gte: 1.1.0
tags:
- tag_uri: tag:astropy.org:astropy/time/timedelta-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/time/timedelta-1.0.0
  title: Represents an instance of TimeDelta from astropy
  description: |-
    Represents the time difference between two times.
- tag_uri: tag:astropy.org:astropy/fits/fits-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/fits/fits-1.0.0
  title: A FITS file inside of an ASDF file.
  description: |-
    This schema is useful for distributing ASDF files that can
    automatically be converted to FITS files by specifying the exact
    content of the resulting FITS file.

    Not all kinds of data in FITS are directly representable in ASDF.
    For example, applying an offset and scale to the data using the
    `BZERO` and `BSCALE` keywords.  In these cases, it will not be
    possible to store the data in the native format from FITS and also
    be accessible in its proper form in the ASDF file.

    Only image and binary table extensions are supported.
- tag_uri: tag:astropy.org:astropy/table/table-1.1.0
  schema_uri: http://astropy.org/schemas/astropy/table/table-1.1.0
  title: A table.
  description: |-
    A table is represented as a list of columns, where each entry is a
    [column](ref:http://stsci.edu/schemas/asdf/core/column-1.0.0)
    object, containing the data and some additional information.

    The data itself may be stored inline as text, or in binary in either
    row- or column-major order by use of the `strides` property on the
    individual column arrays.

    Each column in the table must have the same first (slowest moving)
    dimension.
- tag_uri: tag:astropy.org:astropy/transform/units_mapping-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/transform/units_mapping-1.0.0
  title: Mapper that operates on the units of the input.
  description: |-
    This transform operates on the units of the input, first converting to
    the expected input units, then assigning replacement output units without
    further conversion.
- tag_uri: tag:astropy.org:astropy/table/ndarraymixin-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/table/ndarraymixin-1.0.0
  title: NdarrayMixin column.
  description: |-
    Represents an astropy.table.NdarrayMixin instance.
