id: asdf://astropy.org/astropy/manifests/astropy-1.0.0
extension_uri: asdf://astropy.org/astropy/extensions/astropy-1.0.0
title: Astropy extension 1.0.0
description: |-
  A set of tags for serializing astropy objects.  This does not include most
  model classes, which are handled by an implementation of the ASDF
  transform extension.
asdf_standard_requirement:
  gte: 1.1.0
tags:
- tag_uri: tag:astropy.org:astropy/coordinates/longitude-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/longitude-1.0.0
  title: Represents longitude-like angles.
  description: |-
    Longitude-like angle(s) which are wrapped within a contiguous 360 degree range.
- tag_uri: tag:astropy.org:astropy/coordinates/spectralcoord-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/spectralcoord-1.0.0
  title: Represents a SpectralCoord object from astropy
- tag_uri: tag:astropy.org:astropy/coordinates/latitude-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/latitude-1.0.0
  title: Represents latitude-like angles.
  description: |-
    Represents latitude-like angle(s) which must be in the range -90 to +90 deg.
- tag_uri: tag:astropy.org:astropy/coordinates/representation-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/representation-1.0.0
  title: Representation of points or differentials in two or three dimensional space.
  description: |-
    Representation of points or differentials in two or three dimensional space.
- tag_uri: tag:astropy.org:astropy/coordinates/skycoord-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/skycoord-1.0.0
  title: Represents a SkyCoord object from astropy
- tag_uri: tag:astropy.org:astropy/coordinates/angle-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/angle-1.0.0
  title: Represents an Angle.
  description: |-
    This object represents a subtype of Quantity which has units equivalent to radians or degrees.
- tag_uri: tag:astropy.org:astropy/coordinates/earthlocation-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/earthlocation-1.0.0
  title: Represents EarthLocation objects from astropy.
  description: |-
    Location on the Earth.
- tag_uri: tag:astropy.org:astropy/coordinates/frames/fk5-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/frames/fk5-1.0.0
  title: Represents a FK5 coordinate object from astropy
- tag_uri: tag:astropy.org:astropy/coordinates/frames/itrs-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/frames/itrs-1.0.0
  title: Represents a ITRS coordinate object from astropy
- tag_uri: tag:astropy.org:astropy/coordinates/frames/icrs-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/frames/icrs-1.0.0
  title: Represents an ICRS coordinate object from astropy (deprecated format).
- tag_uri: tag:astropy.org:astropy/coordinates/frames/icrs-1.1.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/frames/icrs-1.1.0
  title: Represents an ICRS coordinate object from astropy.
- tag_uri: tag:astropy.org:astropy/coordinates/frames/galactocentric-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/frames/galactocentric-1.0.0
  title: Represents an galactocentric coordinate object from astropy
- tag_uri: tag:astropy.org:astropy/coordinates/frames/baseframe-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/frames/baseframe-1.0.0
  title: Represents a coordinate frame object from astropy
  description: |-
    This schema is designed to be extended by other schemas to restrict the
    allowable frame_attributes.
- tag_uri: tag:astropy.org:astropy/coordinates/frames/precessedgeocentric-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/frames/precessedgeocentric-1.0.0
  title: Represents a PrecessedGeocentric coordinate object from astropy
- tag_uri: tag:astropy.org:astropy/coordinates/frames/galactic-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/frames/galactic-1.0.0
  title: Represents an Galactic coordinate object from astropy.
- tag_uri: tag:astropy.org:astropy/coordinates/frames/fk4noeterms-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/frames/fk4noeterms-1.0.0
  title: Represents a FK4NoETerms coordinate object from astropy
- tag_uri: tag:astropy.org:astropy/coordinates/frames/icrs-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/frames/icrs-1.0.0
  title: Represents an ICRS coordinate object from astropy
  description: |-
    This object represents the right ascension (RA) and declination of an ICRS
    coordinate or frame. The ICRS class contains additional fields that may be
    useful to add here in the future.
- tag_uri: tag:astropy.org:astropy/coordinates/frames/cirs-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/frames/cirs-1.0.0
  title: Represents a CIRS coordinate object from astropy
- tag_uri: tag:astropy.org:astropy/coordinates/frames/fk4-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/frames/fk4-1.0.0
  title: Represents a FK4 coordinate object from astropy
- tag_uri: tag:astropy.org:astropy/coordinates/frames/gcrs-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/coordinates/frames/gcrs-1.0.0
  title: Represents a GCRS coordinate object from astropy
- tag_uri: tag:astropy.org:astropy/time/timedelta-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/time/timedelta-1.0.0
  title: Represents an instance of TimeDelta from astropy
  description: |-
    Represents the time difference between two times.
- tag_uri: tag:astropy.org:astropy/units/equivalency-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/units/equivalency-1.0.0
  title: Represents unit equivalency.
  description: |-
    Supports serialization of equivalencies between units
    in certain contexts
- tag_uri: tag:astropy.org:astropy/fits/fits-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/fits/fits-1.0.0
  title: A FITS file inside of an ASDF file.
  description: |-
    This schema is useful for distributing ASDF files that can
    automatically be converted to FITS files by specifying the exact
    content of the resulting FITS file.

    Not all kinds of data in FITS are directly representable in ASDF.
    For example, applying an offset and scale to the data using the
    `BZERO` and `BSCALE` keywords.  In these cases, it will not be
    possible to store the data in the native format from FITS and also
    be accessible in its proper form in the ASDF file.

    Only image and binary table extensions are supported.
- tag_uri: tag:astropy.org:astropy/table/table-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/table/table-1.0.0
  title: A table.
  description: |-
    A table is represented as a list of columns, where each entry is a
    [column](ref:http://stsci.edu/schemas/asdf/core/column-1.0.0)
    object, containing the data and some additional information.

    The data itself may be stored inline as text, or in binary in either
    row- or column-major order by use of the `strides` property on the
    individual column arrays.

    Each column in the table must have the same first (slowest moving)
    dimension.
- tag_uri: tag:astropy.org:astropy/transform/units_mapping-1.0.0
  schema_uri: http://astropy.org/schemas/astropy/transform/units_mapping-1.0.0
  title: Mapper that operates on the units of the input.
  description: |-
    This transform operates on the units of the input, first converting to
    the expected input units, then assigning replacement output units without
    further conversion.
